### PR TITLE
Documentation for image generators

### PR DESCRIPTION
**Pull request by nicolasbeauvais**
Documentation for https://github.com/spatie/laravel-medialibrary/pull/346

I only made half the work but you can already take a look at it and give me some suggestion to improve the documentation quality :)

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you for working on this! I'll give you some feedback in the coming days.

**Comment by freekmurze** [comment]
I took a quick glance at your changes and it all seems ok. Please complete it and let me know when you're done. 

I'll rework it a little bit to fit my personal preference.

**Comment by freekmurze** [comment]
Nice work, can I pull these and make some nitpick changes? Or are you planning to work a little further on this?

**Comment by nicolasbeauvais** [comment]
yes go ahead, I do not have any changes planned for now on the doc :)

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
