### PR TITLE
add enum documentation

### PR DESCRIPTION
**Pull request by Gummibeer**
https://github.com/spatie/enum/pull/18

### CODE REVIEW

**Comment by Gummibeer** [comment]
v2 is released https://github.com/spatie/enum/releases/tag/2.0.0

**Comment by brendt** [comment]
@willemvb can you come up with a good image for this one?

**Comment by brendt** [comment]
One remark: I find the "compare usage" a little confusing because we're using booleans. I think i'd be better to show an example with `status` or something alike, to avoid confusion altogether.

Instead of:

```php
BoolEnum::true()->isTrue(); // true
BoolEnum::isTrue(0); // false
```

```php
StatusEnum::draft()->isDraft();
StatusEnum::isPublished(StatusEnum::draft());
StatusEnum::isPublished('archived');
```

Also let's mention that if you want, you can add the `is*` methods as doc blocks on your specific enum  classes.

**Comment by brendt** [comment]
Also, let's keep the basic usage example on `/enum/v2/usage/enum-setup` more clean at first. 

Again let's use the status enum example, and don't add the `is*` doc blocks until the comparing section

**Comment by Gummibeer** [comment]
@brendt have replaced the `BoolEnum` by `WeekDayEnum`.

**Comment by brendt** [comment]
Thanks!

**Comment by Gummibeer** [comment]
poke @brendt

**Comment by brendt** [comment]
I lost track of this one, thanks for the poke! @willemvb will take a look at an appropriate image this week.

**Comment by willemvb** [comment]
Done!

**Pull request merged**
