### PR TITLE
Small improvements/fixes to the getting started documentation

### PR DESCRIPTION
**Pull request by Cayan**

### CODE REVIEW

**Review by freekmurze — CHANGES_REQUESTED** [review]
In the latest version of the package this property doesn't need to be `public` anymore. Could you remove those changes from this PR?

**Comment by Cayan** [comment]
Oh, fixing it

**Review by Cayan — COMMENTED** [review]
all requested changes were applied

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
