### PR TITLE
Document the --ids option of the RegenerateCommand

### PR DESCRIPTION
**Pull request by BARNZ**

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
Iirc `--ids=1,2,3` works too

**Comment by BARNZ** [comment]
Hah! I did try that at first, but that doesn't seem to be the case:

image

It just passes that option through to the query builder as a single string. Possibly a bug?

**Comment by BARNZ** [comment]
When using just `--ids=1,2,3` `$this->option('ids')` actually returns an array in the format:

```
[
  0 => "1,2,3"
]
```
and bypasses this section in the code:

image

**Comment by sebastiandedeyne** [comment]
Gonna merge this in when the intended behaviour is fixed 👌

**Pull request merged**
